baseURL = 'http://pitch.pantrypoints.com/'
languageCode = 'en-us'
title = 'Pantrypoints pitch'

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

